settings:
  username: "itsyourap" # Replace with your username or comment out this line
  commit_msg: "Update recent activities"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events: ["comments", "star", "create_repo", "fork", "wiki"]
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+05:30"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "{NUM}. "
  ignored_repos: ["itsyourap/itsyourap"]
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  push: "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"